version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - redis
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    volumes:
      - ./client:/app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
